#!/usr/bin/env bash
# Remove every .sh generated by bat2sh under the examples/ tree.
# The two helper scripts themselves are kept.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
found=$(find "$HERE" -type f -name '*.sh' \
             ! -name 'remove_generated.sh' \
             ! -name 'generate_examples.sh')
if [ -z "$found" ]; then
    echo "No generated .sh files under $HERE"
    exit 0
fi
echo "$found"
find "$HERE" -type f -name '*.sh' \
     ! -name 'remove_generated.sh' \
     ! -name 'generate_examples.sh' -delete
echo "Removed."
